export const landingCopy = {
  en: {
    nav: {
      services: "Services",
      work: "Work",
      about: "About",
      insights: "Insights",
      contact: "Contact",
      cta: "Let's Sync",
      openMenu: "Open navigation menu",
    },
    hero: {
      note: ["Different Disciplines", "Same Vision."],
      actions: ["Create", "Connect", "Grow"],
      polaroid: ["Good Brands", "Better People"],
      phone: ["All Around", "the", "Sync"],
      services: ["SOCIAL", "BRANDING", "CONTENT", "PHOTO & VIDEO", "WEB & TECH"],
      title: ["Your Brand,", "In Sync,", "Everywhere."],
      cta: "Let's Sync",
      story: "Watch Our Story",
    },
    services: {
      title: ["Everything", "Your Brand", "Needs to Grow."],
      cta: "Explore Our Services",
      items: [
        ["Social", "& Community"],
        ["Branding", "& Creative"],
        ["Photo", "& Video"],
        ["Web &", "Technology"],
      ],
      notes: ["Ideas", "People", "Places", "Progress"],
    },
    projects: {
      title: ["Real Brands.", "Real Results."],
      stats: ["Brands", "Growth", "Satisfaction"],
      cta: "View All Work",
      cards: [
        ["A Global", "Community"],
        ["From Vision", "to Identity"],
        ["Stories", "That Move"],
      ],
    },
    vision: {
      title: ["Same Vision.", "Bigger Impact."],
      values: [
        ["People", "First"],
        ["Creative", "Thinking"],
        ["Tech", "Driven"],
        ["Results", "That Matter"],
      ],
      pins: ["IDEAS", "PEOPLE", "PLACES", "PROGRESS"],
      cta: "See How We Work",
      team: ["One Team.", "Worldwide."],
      connected: ["More", "Connected", "Than Ever"],
    },
    contact: {
      eyebrow: "Let's create together",
      title: ["Ready to", "bring your vision", "to life?"],
      name: "Name",
      namePlaceholder: "Your name",
      email: "Email",
      emailPlaceholder: "you@company.com",
      company: "Company",
      companyPlaceholder: "Your company",
      message: "What do you need?",
      messagePlaceholder: "Tell us a bit about your project...",
      send: "Send message",
      sending: "Sending...",
      success: "Message sent successfully!",
      error: "Something went wrong. Please try again.",
      note: ["Good brands", "start here."],
      callTitle: "Prefer a call?",
      callDescription: "Book a free 15-minute call to discuss your project.",
      callCta: "Book a call",
    },
    footer: {
      lines: ["Strategy. Content. Social.", "Brand and Tech — All in Sync."],
      rights: "All rights reserved.",
      tagline: "Create. Connect. Grow.",
    },
  },
  pt: {
    nav: {
      services: "Serviços",
      work: "Projetos",
      about: "Sobre",
      insights: "Conteúdos",
      contact: "Contato",
      cta: "Vamos sincronizar",
      openMenu: "Abrir menu de navegação",
    },
    hero: {
      note: ["Diferentes disciplinas", "Uma só visão."],
      actions: ["Criar", "Conectar", "Crescer"],
      polaroid: ["Boas marcas", "Pessoas melhores"],
      phone: ["Tudo", "em", "Sintonia"],
      services: ["SOCIAL", "BRANDING", "CONTEÚDO", "FOTO & VÍDEO", "WEB & TECH"],
      title: ["Sua marca,", "Em sintonia,", "Em todo lugar."],
      cta: "Vamos sincronizar",
      story: "Conheça nossa história",
    },
    services: {
      title: ["Tudo que", "sua marca precisa", "para crescer."],
      cta: "Conheça nossos serviços",
      items: [
        ["Social", "& Comunidade"],
        ["Branding", "& Criação"],
        ["Foto", "& Vídeo"],
        ["Web &", "Tecnologia"],
      ],
      notes: ["Ideias", "Pessoas", "Lugares", "Progresso"],
    },
    projects: {
      title: ["Marcas reais.", "Resultados reais."],
      stats: ["Marcas", "Crescimento", "Satisfação"],
      cta: "Ver todos os projetos",
      cards: [
        ["Uma comunidade", "global"],
        ["Da visão", "à identidade"],
        ["Histórias", "que movem"],
      ],
    },
    vision: {
      title: ["A mesma visão.", "Um impacto maior."],
      values: [
        ["Pessoas", "primeiro"],
        ["Pensamento", "criativo"],
        ["Movidos por", "tecnologia"],
        ["Resultados", "que importam"],
      ],
      pins: ["IDEIAS", "PESSOAS", "LUGARES", "PROGRESSO"],
      cta: "Veja como trabalhamos",
      team: ["Um time.", "No mundo todo."],
      connected: ["Mais", "conectados", "que nunca"],
    },
    contact: {
      eyebrow: "Vamos criar juntos",
      title: ["Pronto para", "dar vida à", "sua visão?"],
      name: "Nome",
      namePlaceholder: "Seu nome",
      email: "E-mail",
      emailPlaceholder: "voce@empresa.com",
      company: "Empresa",
      companyPlaceholder: "Sua empresa",
      message: "Do que você precisa?",
      messagePlaceholder: "Conte um pouco sobre seu projeto...",
      send: "Enviar mensagem",
      sending: "Enviando...",
      success: "Mensagem enviada com sucesso!",
      error: "Algo deu errado. Tente novamente.",
      note: ["Boas marcas", "começam aqui."],
      callTitle: "Prefere conversar?",
      callDescription: "Agende uma conversa gratuita de 15 minutos sobre seu projeto.",
      callCta: "Agendar conversa",
    },
    footer: {
      lines: ["Estratégia. Conteúdo. Social.", "Marca e tecnologia — tudo em sintonia."],
      rights: "Todos os direitos reservados.",
      tagline: "Criar. Conectar. Crescer.",
    },
  },
} as const
